FROM registry.fedoraproject.org/fedora:36 AS fetch

ARG VERSION="23.0"

ADD https://bitcoincore.org/bin/bitcoin-core-${VERSION}/bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz .
ADD https://bitcoincore.org/bin/bitcoin-core-${VERSION}/SHA256SUMS .
ADD https://bitcoincore.org/bin/bitcoin-core-${VERSION}/SHA256SUMS.asc .

## HACK: https://github.com/bitcoin/bitcoin/issues/25022
ADD https://raw.githubusercontent.com/Kvaciral/kvaciral/main/kvaciral.asc .
RUN gpg --import kvaciral.asc

## Verify retieved archive
RUN gpg --keyserver hkps://keys.openpgp.org --auto-key-retrieve --trust-model always --verify SHA256SUMS.asc SHA256SUMS
RUN sha256sum --ignore-missing --check SHA256SUMS

## Unpacks bitcoin-${VERSION} directory into WORKDIR
RUN tar -xzf bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz

FROM registry.fedoraproject.org/fedora-minimal:36

ARG VERSION="23.0"

RUN mkdir -p /etc/bitcoin
COPY bitcoin.conf /etc/bitcoin

## bitcoin-core's linux build maps to an FHS tree... Just dump it into the image's /usr tree
COPY --from=fetch bitcoin-${VERSION} /usr
ENTRYPOINT [ "/usr/bin/bitcoind" ]
