ARG VERSION="24.1"

FROM registry.fedoraproject.org/fedora:38 AS fetch
ARG VERSION

ADD https://bitcoincore.org/bin/bitcoin-core-${VERSION}/bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz .
ADD https://bitcoincore.org/bin/bitcoin-core-${VERSION}/SHA256SUMS .
ADD https://bitcoincore.org/bin/bitcoin-core-${VERSION}/SHA256SUMS.asc .

## From https://bitcoincore.org/en/download/
RUN dnf install -y git
RUN git clone https://github.com/bitcoin-core/guix.sigs
RUN gpg --import guix.sigs/builder-keys/*

## Verify retieved archive
RUN gpg --verify SHA256SUMS.asc
RUN sha256sum --ignore-missing --check SHA256SUMS

## Unpacks bitcoin-${VERSION} directory into WORKDIR
RUN tar -xzf bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz

FROM registry.fedoraproject.org/fedora-minimal:38
ARG VERSION

RUN mkdir -p /etc/bitcoin
COPY bitcoin.conf /etc/bitcoin/

## bitcoin-core's linux build maps to an FHS tree... Just dump it into the image's /usr tree
COPY --from=fetch bitcoin-${VERSION} /usr
ENTRYPOINT [ "/usr/bin/bitcoind" ]
