FROM docker.io/node:18.2-buster AS fetch

ARG VERSION="3.3.0"

ADD https://github.com/janoside/btc-rpc-explorer/archive/refs/tags/v${VERSION}.tar.gz .
RUN tar -vxf v${VERSION}.tar.gz

WORKDIR /btc-rpc-explorer-${VERSION}
RUN npm install

FROM node:18.2-slim

ARG VERSION="3.3.0"
COPY --from=fetch /btc-rpc-explorer-${VERSION} /opt/explorer

ENTRYPOINT [ "/usr/local/bin/node", "/opt/explorer/bin/cli.js" ]
