## Target version to package
ARG VERSION="2.4.0"

## Build javascript from type-script project source
FROM docker.io/node:16 AS build
ARG VERSION

ADD https://github.com/mempool/mempool/archive/refs/tags/v${VERSION}.tar.gz .
RUN tar -xvzf v${VERSION}.tar.gz mempool-${VERSION}/backend mempool-${VERSION}/frontend

WORKDIR /mempool-${VERSION}/backend
RUN npm install
RUN npm run build

WORKDIR /mempool-${VERSION}/frontend
RUN apt-get update && apt-get install -y rsync
RUN npm install --omit=dev --omit=optional
RUN npm run build

## Build an output FS tre to be copeied into the minimal static-server image
RUN mkdir -p tree/var/lib
RUN cp -r dist/mempool/browser/en-US/ tree/var/lib/www
## Create an empty file for a health-check endpoint
RUN touch tree/var/lib/www/liveness

FROM ghcr.io/jmanero/static:latest AS frontend
ARG VERSION

## Deploy the english UI version
COPY --from=build /mempool-${VERSION}/frontend/tree /
CMD [ "--listen", "0.0.0.0:9807", "/var/lib/www" ]

FROM docker.io/node:16-slim AS backend
ARG VERSION

COPY --from=build /mempool-${VERSION}/backend/dist /opt/mempool/dist
COPY --from=build /mempool-${VERSION}/backend/node_modules /opt/mempool/node_modules
COPY --from=build /mempool-${VERSION}/backend/package.json /mempool-${VERSION}/backend/package-lock.json /opt/mempool/

COPY mempool-config.json /opt/mempool/

WORKDIR /opt/mempool
CMD [ "./dist/index.js" ]
