## bitcoind resources
auth            = "electrs:electrs"
daemon_rpc_addr = "bitcoind:8332"
daemon_p2p_addr = "bitcoind:8333"

## bitcoin == mainnet
network = "bitcoin"

db_dir = "/data"

electrum_rpc_addr = "0.0.0.0:50001"
monitoring_addr   = "0.0.0.0:50042"

log_filters = "INFO"
